'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientForm

  '''<summary>
  '''lastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lastName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''middleName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents middleName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''firstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents firstName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''address control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents address As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''city control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents city As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''state control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents state As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''zip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents zip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''homePhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents homePhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cellPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cellPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''treatmentLocation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents treatmentLocation As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''emailAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents emailAddress As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''dateOfBirth control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dateOfBirth As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''numberOfChildren control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents numberOfChildren As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''employer control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents employer As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''language control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents language As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''race control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents race As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''status control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents status As Global.System.Web.UI.WebControls.DropDownList
End Class
